apiVersion: apps/v1
kind: Deployment
metadata:
  name: server2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: nginx
        image: a7ryan/cloudenv:server2Image
        ports:
        - containerPort: 80

# ip -> 10.244.0.8
